import { LLMService } from "./src/application/services/LLMService";
import { RawThreadData } from "./src/application/services/RedditService";

// Mock data for testing
const mockRedditData: RawThreadData = {
  title: "AITA for telling my roommate that her cooking smells terrible?",
  url: "https://reddit.com/r/AmItheAsshole/comments/test",
  author: "TestUser123",
  content:
    "So I (22F) live with my roommate Sarah (23F) in a small apartment. She loves to cook these really exotic dishes with strong spices, and honestly, the smell is overwhelming. It fills the entire apartment and sometimes makes me feel nauseous. Yesterday I finally told her that her cooking smells terrible and asked if she could cook less pungent food. She got really upset and said I was being culturally insensitive. AITA?",
  comments: [
    {
      author: "RedditWisdom",
      content:
        "NTA - You have a right to feel comfortable in your own home. Maybe you could suggest she use the kitchen fan or cook when you're not around?",
      upvotes: 245,
      depth: 0,
    },
    {
      author: "CookingExpert",
      content:
        "YTA - You could have approached this more diplomatically. Food is often tied to culture and identity.",
      upvotes: 156,
      depth: 0,
    },
  ],
  upvotes: 1547,
  subreddit: "AmItheAsshole",
};

async function testLLMWithApiKey() {
  console.log("🚀 Testing LLM Service with Gemini 2.0 Flash...\n");

  // Check if API key is set
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey || apiKey === "your_real_api_key_goes_here") {
    console.log("⚠️  No valid API key found!");
    console.log("📝 To test with real Gemini API:");
    console.log(
      "   1. Get API key from: https://makersuite.google.com/app/apikey"
    );
    console.log(
      "   2. Edit .env file and replace: GEMINI_API_KEY=your_actual_key"
    );
    console.log("   3. Run this test again\n");

    console.log("🔄 Running with mock fallback for now...\n");
  } else {
    console.log("✅ API key found! Testing with real Gemini API...\n");
  }

  try {
    const llmService = new LLMService();

    console.log("📝 Generating script from Reddit thread...");
    const script = await llmService.generateStructuredScript(mockRedditData);

    console.log("✅ Script generated successfully!\n");
    console.log("📋 Script Details:");
    console.log(`- ID: ${script.id}`);
    console.log(`- Background: ${script.background}`);
    console.log(`- Characters: ${script.characters.join(", ")}`);
    console.log(`- Number of dialogue lines: ${script.lines.length}\n`);

    console.log("🎭 Generated Script:");
    console.log("=".repeat(50));
    script.lines.forEach((line: any, index: number) => {
      console.log(`${index + 1}. [${line.speaker}]: "${line.text}"`);
      console.log("");
    });

    if (!apiKey || apiKey === "your_real_api_key_goes_here") {
      console.log(
        "💡 This is mock data. With a real API key, you'll get AI-generated scripts!"
      );
    } else {
      console.log("🎉 This script was generated by Gemini 2.0 Flash!");
    }
  } catch (error) {
    console.error("❌ Error testing LLM service:", error);
  }
}

// Run the test
testLLMWithApiKey();
